### ISSUE TITLE
About PCA model of per-vertex albedo

### ISSUE THREAD

**Issue by zomkey** [zhuhao-nju/facescape#10]
Hi，thanks for your great work！ 
I want to train 3DMM model with albedo, but I cannot find PCA model of per-vertex albedo in released dataset. I want to ask whether PCA model of per-vertex albedo will be released ?
Hope for your reply, thank you very much!

**Comment by zhuhao-nju** [comment]
Thanks! @zomkey 
Currently we we mainly focus on solving geometry and have not generated parametric model for albedo.  So we are sorry that the PCA model of abledo will not be released in the near future, but we probably add it to our long-term plan.
