### ISSUE TITLE
关于裁剪出人脸区域的问题

### ISSUE THREAD

**Issue by 123456789asdfjkl** [zhuhao-nju/facescape#108]
感谢您的杰出工作，我在裁剪人脸区域时发现bm_model['fv_indices_front']这个好像少了一些面，导致使用其裁剪出来的人脸部分在嘴部区域出现了孔洞，使用的是facescape_bm_v1.6_847_50_52_id_front.npz

**Comment by lyx323** [comment]
已收到

**Comment by 123456789asdfjkl** [comment]
此问题已解决（大家更新一下文件facescape_bm.py就可以 了），感谢朱老师的解答
