### ISSUE TITLE
关于example rig的52个example表情

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [zhuhao-nju/facescape#11]
非常赞的工作！

可以分享下facescape拓扑下，进行example rig时参考的52个表情obj么

**Comment by yanght321** [comment]
@ZHANG-SHI-CHANG 
Hi，我们把52个模版的obj上传到了google drive：https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing

**Comment by ZHANG-SHI-CHANG** [comment]
> https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing

赞！感谢！

**Comment by ZHANG-SHI-CHANG** [comment]
> @ZHANG-SHI-CHANG
> Hi，我们把52个模版的obj上传到了google drive：https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing

请问模板的形变怎么获得的呢，动画师手K的吗

**Comment by kuangcy1998** [comment]
> > @ZHANG-SHI-CHANG
> > Hi，我们把52个模版的obj上传到了google drive：https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing
> 
> 请问模板的形变怎么获得的呢，动画师手K的吗

我也很想问下这个问题

**Comment by yanght321** [comment]
> > > @ZHANG-SHI-CHANG
> > > Hi，我们把52个模版的obj上传到了google drive：https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing
> > 
> > 
> > 请问模板的形变怎么获得的呢，动画师手K的吗
> 
> 我也很想问下这个问题

是的，模版的形变是动画师预先设计的

**Comment by polukeadria** [comment]
> > @ZHANG-SHI-CHANG
> > Hi，我们把52个模版的obj上传到了google drive：https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing
> 
> 请问模板的形变怎么获得的呢，动画师手K的吗

Are these templates rigged according to apple's 52 blendshapes? Could you please label the blendshape's name for each template?
