### ISSUE TITLE
关于bilinear中立脸的问题

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [zhuhao-nju/facescape#12]
非常赞的工作！

我统计了下给出的bilinear模型，给出了888个人的id特征，抽样出888个人的数据之后，发现有652id的nature状态是张着嘴的，我认为这是不合理的，会造成blendshape表达不准确，这种现象有办法补救吗

**Comment by zhuhao-nju** [comment]
感谢反馈！出现这个问题是因为从template mesh适应raw scan mesh的结果不够准确，具体来说是NICP的优化结果没有完全包裹唇部接缝部位。目前我们还没有很好的解决方法，随着registeration研究的进步和精度的提高，我们可能会在未来对数据进行更新。

**Comment by ZHANG-SHI-CHANG** [comment]
> mesh

你们尝试过用warp3d，它可以实现非常好的效果，在影视动画界非常常用

**Comment by zhuhao-nju** [comment]
> > mesh
> 
> 你们尝试过用warp3d，它可以实现非常好的效果，在影视动画界非常常用

谢谢~ 我们会尝试这个工具
