### ISSUE TITLE
关于id的个数

### ISSUE THREAD

**Issue by MandyMo** [zhuhao-nju/facescape#13]
首选，这是一个非常棒的工作，近期下载了你们的数据用于学术研究，但是我发现有如下问题：

paper中claim有900个id，但是数据的 core_tensor却只有50个 id，请问这个是符合预期的么

**Comment by yanght321** [comment]
Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。

**Comment by MandyMo** [comment]
> Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。


非常感谢你的回复，我从你们的paper里面 (Figure 3)发现300个id参数的模型的表达能力比50个id参数的表达能力要强很多，不知道你们能否release 300个id 参数的模型。


从Figure 3中可发现，50个id 参数的模型与facewarehouse相比，其表达能力差不多；但是300个id参数的模型的表达能力较facewarehouse要好很多。

补充一点：facewarehouse放出了150个id参数的模型，我最近的research里面用的是150个id参数的facewarehouse

**Comment by cLEARLoVE00** [comment]
> Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。



> > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> 
> 非常感谢你的回复，我从你们的paper里面 (Figure 3)发现300个id参数的模型的表达能力比50个id参数的表达能力要强很多，不知道你们能否release 300个id 参数的模型。
> 
> 从Figure 3中可发现，50个id 参数的模型与facewarehouse相比，其表达能力差不多；但是300个id参数的模型的表达能力较facewarehouse要好很多。
> 
> 补充一点：facewarehouse放出了150个id参数的模型，我最近的research里面用的是150个id参数的facewarehouse

can you share a link about facewarehouse dataset?I do 3D face reconstruction job,need facewarehouse dataset.Thank you

**Comment by MandyMo** [comment]
> > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> 
> > > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> > 
> > 
> > 非常感谢你的回复，我从你们的paper里面 (Figure 3)发现300个id参数的模型的表达能力比50个id参数的表达能力要强很多，不知道你们能否release 300个id 参数的模型。
> > 从Figure 3中可发现，50个id 参数的模型与facewarehouse相比，其表达能力差不多；但是300个id参数的模型的表达能力较facewarehouse要好很多。
> > 补充一点：facewarehouse放出了150个id参数的模型，我最近的research里面用的是150个id参数的facewarehouse
> 
> can you share a link about facewarehouse dataset?I do 3D face reconstruction job,need facewarehouse dataset.Thank you

No I can't share facewarehouse to you, it would be better if you shall apply it from Dr. Zhou.

**Comment by MandyMo** [comment]
> Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。

你可能误解我的意思了，你现在放的core_tensor是50维的id，但是你paper里面的Fig 3表明，50维id模型的表达能力跟facewarehouse差不多，同时稍劣于FLAME；但是300维id模型的表达能力还可以。所以个人认为，可能300维的id的模型是大家需要的。

**Comment by cLEARLoVE00** [comment]
> Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
你好，我提交了你们网站的数据申请，但是一直没有回复，你可以分享一下数据下载的链接或者恢复一下我的邮件么，我主要用于3D人脸重建的研究，希望你们可以尽快回复，谢谢！

**Comment by MandyMo** [comment]
> > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> > 你好，我提交了你们网站的数据申请，但是一直没有回复，你可以分享一下数据下载的链接或者恢复一下我的邮件么，我主要用于3D人脸重建的研究，希望你们可以尽快回复，谢谢！

I am sorry, I am not a team member inDr. Zhou.
Due to the license limitation, I can't share Facewarhouse to you personally .

**Comment by cLEARLoVE00** [comment]
> > > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> > > 你好，我提交了你们网站的数据申请，但是一直没有回复，你可以分享一下数据下载的链接或者恢复一下我的邮件么，我主要用于3D人脸重建的研究，希望你们可以尽快回复，谢谢！
> 
> I am sorry, I am not a team member inDr. Zhou.
> Due to the license limitation, I can't share Facewarhouse to you personally 

我是想申请FaceScape数据集的，但是网站没有给我回复，打扰打你了不好意思。

**Comment by yanght321** [comment]
> > Hi，core_tensor是从原始模型得到的参数模型，里面的50个id参数是原始id降维得到的。你可以通过factors_id近似恢复出原始模型。在我们的网站可以下载847个人的原始对齐之后的模型(Models)。
> 
> 非常感谢你的回复，我从你们的paper里面 (Figure 3)发现300个id参数的模型的表达能力比50个id参数的表达能力要强很多，不知道你们能否release 300个id 参数的模型。
> 
> 从Figure 3中可发现，50个id 参数的模型与facewarehouse相比，其表达能力差不多；但是300个id参数的模型的表达能力较facewarehouse要好很多。
> 
> 补充一点：facewarehouse放出了150个id参数的模型，我最近的research里面用的是150个id参数的facewarehouse

现在我们的网站(https://facescape.nju.edu.cn/Page_Data/)上加上了300个id参数的模型可以下载。但是注意我们生成300个id参数的模型主要是为了与FLAME对比，基于单张图片拟合3DMM我们用的还是50个id的模型。
