### ISSUE TITLE
如何从头部模型中截取脸部

### ISSUE THREAD

**Issue by Hzj199** [zhuhao-nju/facescape#14]
论文实验中只用了脸部，请问要怎么样才能从数据集中截取出脸部？

**Comment by zhuhao-nju** [comment]
Hi @Hzj199 ，
我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)

**Comment by Hzj199** [comment]
非常感谢！！！

**Comment by Hzj199** [comment]
> Hi @Hzj199 ，
> 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)

非常感谢！！！

**Comment by zhuhao-nju** [comment]
> > Hi @Hzj199 ，
> > 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> > ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)
> 
> 非常感谢！！！所有的图像都共用一张贴图吗？

是的，论文实验的面部提取共用这一张贴图。

**Comment by Hzj199** [comment]
> > > Hi @Hzj199 ，
> > > 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> > > ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)
> > 
> > 
> > 非常感谢！！！所有的图像都共用一张贴图吗？
> 
> 是的，论文实验的面部提取共用这一张贴图。

谢谢！！！

**Comment by Hzj199** [comment]
> > > Hi @Hzj199 ，
> > > 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> > > ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)
> > 
> > 
> > 非常感谢！！！所有的图像都共用一张贴图吗？
> 
> 是的，论文实验的面部提取共用这一张贴图。

请问您使用什么方法通过贴图截取脸部模型的？我本打算用open3d读取obj文件，通过颜色来截取，但是open3d读取obj文件后返回的vertex_color都是[1,1,1]。

**Comment by zhuhao-nju** [comment]
> > > > Hi @Hzj199 ，
> > > > 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> > > > ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)
> > > 
> > > 
> > > 非常感谢！！！所有的图像都共用一张贴图吗？
> > 
> > 
> > 是的，论文实验的面部提取共用这一张贴图。
> 
> 请问您使用什么方法通过贴图截取脸部模型的？我本打算用open3d读取obj文件，通过颜色来截取，但是open3d读取obj文件后返回的vertex_color都是[1,1,1]。

需要使用纹理贴图，不是顶点着色，因为我们的模型没有提供vertex_color。具体判断某个顶点是否是面部的方法是，查找该顶点对应的二维纹理坐标（texture coordinate），而后通过纹理坐标查询上面提供的mask贴图中对应像素值  >0：面部；==0：非面部。

**Comment by Hzj199** [comment]
> > > > > Hi @Hzj199 ，
> > > > > 我们使用了标注面部区域的纹理贴图，如下，通过渲染得到面部的mask，进而提取出面部。论文进行的实验是重建出完整头部的，只是在渲染时只展示了面部。
> > > > > ![white](https://user-images.githubusercontent.com/40872587/86399298-93b10b00-bcd9-11ea-9434-6dfaa45e5b8c.png)
> > > > 
> > > > 
> > > > 非常感谢！！！所有的图像都共用一张贴图吗？
> > > 
> > > 
> > > 是的，论文实验的面部提取共用这一张贴图。
> > 
> > 
> > 请问您使用什么方法通过贴图截取脸部模型的？我本打算用open3d读取obj文件，通过颜色来截取，但是open3d读取obj文件后返回的vertex_color都是[1,1,1]。
> 
> 需要使用纹理贴图，不是顶点着色，因为我们的模型没有提供vertex_color。具体判断某个顶点是否是面部的方法是，查找该顶点对应的二维纹理坐标（texture coordinate），而后通过纹理坐标查询上面提供的mask贴图中对应像素值 >0：面部；==0：非面部。

谢谢！！！
