### ISSUE TITLE
requests for supplementary material

### ISSUE THREAD

**Issue by cyj907** [zhuhao-nju/facescape#15]
hello, could you send me a link with the supplementary material?

**Comment by zycliao** [comment]
It's available here
https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Yang_FaceScape_A_Large-Scale_CVPR_2020_supplemental.zip

**Comment by zhuhao-nju** [comment]
> It's available here
> https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Yang_FaceScape_A_Large-Scale_CVPR_2020_supplemental.zip

Thanks for your help! :D

**Comment by cyj907** [comment]
> It's available here
> https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Yang_FaceScape_A_Large-Scale_CVPR_2020_supplemental.zip

thank you very much!
