### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by cLEARLoVE00** [zhuhao-nju/facescape#16]
你好，为什么我验证都通过了而且所有协议也同意了，为什么没有下载链接也没有可以登录下载的地方呢，希望你们可以解答一下，谢谢。![Uploading 86371086...]()

**Comment by zhuhao-nju** [comment]
Hi @cLEARLoVE00 
正常情况下，勾选条款、输入Email和License Key、拖拽滑块、点击Verify后，会跳转到包含下载链接的页面。可以先尝试更换浏览器，如果仍无法下载请使用Chrome完成上述操作，然后将选择右上角选项-->更多工具-->开发者工具，将console选项卡中的内容截图发送给我们，我们会帮助排查问题。
