### ISSUE TITLE
Does the current dataset contain the 3D Morphable Model?

### ISSUE THREAD

**Issue by vikasTmz** [zhuhao-nju/facescape#17]
.

**Comment by zhuhao-nju** [comment]
Yes, 3DMM is provided.

**Comment by Ivy147** [comment]
> Yes, 3DMM is provided.

Hi，zhuhao，first thanks to your great job and your released dataset!
I find that the download models have 26317 points with head,  can I get the index which corresponding to the points in 3DMM with 53490 points?
