### ISSUE TITLE
Can your model points correspond to the BFM model?

### ISSUE THREAD

**Issue by Ivy147** [zhuhao-nju/facescape#18]
Hi，zhuhao，first thanks to your great job and your released dataset!
I find that the download models have 26317 points with head, can I get the index which corresponding to the points in 3DMM with 53490 points like BFM? Because I want to use this two datasets to train together.
I tried to use nicp to register two template and find the closet point as the corresponding ,but since your template is two sparse ,the result can't  keep the uniformity of the points. 
Can you give me some advices?

By the way, why don't I just use NICP to register all the models, because I find that the registration results are not very good for the models with expressions, I hope to solve this problem by sampling the emotive models with a unified correspondence.

**Comment by yanght321** [comment]
Hi,

**Comment by yanght321** [comment]
Hi,
I think you can find the closet points on triangle face instead of closet vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.

**Comment by Ivy147** [comment]
> Hi,
> I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.
Thank you for inspiring me，I will have a try.

**Comment by Ivy147** [comment]
> Hi,
> I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.

Thank you for inspiring me，I will have a try.

**Comment by cLEARLoVE00** [comment]
> > Hi,
> > I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.
> 
> Thank you for inspiring me，I will have a try.

I use dataset 26317 point resigrate 53490 points through Nicp ,but the result is Matrix is not match ,so I want to know your result is good ?

**Comment by Ivy147** [comment]
> > > Hi,
> > > I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.
> > 
> > 
> > Thank you for inspiring me，I will have a try.
> 
> I use dataset 26317 point resigrate 53490 points through Nicp ,but the result is Matrix is not match ,so I want to know your result is good ?

Mine is good，I used [nricp](https://github.com/charlienash/nricp).

**Comment by ChangY-7** [comment]
> Hi,
> I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.

Hello, I am a little confused about this. Is that we should find the closest triangles and use their barycentric coordinates as corresponding? 

Could you explain it more specifically?  Looking forward to the reply, thank you very much!

**Comment by yanght321** [comment]
> > Hi,
> > I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.
> 
> Hello, I am a little confused about this. Is that we should find the closest triangles and use their barycentric coordinates as corresponding?
> 
> Could you explain it more specifically? Looking forward to the reply, thank you very much!

For each vertex of the Facescape model, you can find its closest triangle on the BFM and project the vertex to the closest triangle. Then the barycentric coordinate of the projected point on the triangle can be used as corresponding.

**Comment by ChangY-7** [comment]
> Hi,
> I think you can find the closest points on triangle face instead of closest vertex after nicp registration. Then the calculated barycentric coordinates can be used to sample new models.
> 
> Hello, I am a little confused about this. Is that we should find the closest triangles and use their barycentric coordinates as corresponding?
> Could you explain it more specifically? Looking forward to the reply, thank you very much!
> 
> For each vertex of the Facescape model, you can find its closest triangle on the BFM and project the vertex to the closest triangle. Then the barycentric coordinate of the projected point on the triangle can be used as corresponding.

Oh, I see. Thank you again!

**Comment by vikasTmz** [comment]
@Ivy147 do you have an example result of nricp applied on the template mesh of bfm and facescape? I seem to be suffering from the same issues as OP.

**Comment by Easy-Shu** [comment]
@Ivy147 Have you aleady generated the 3DMM BFM? can you share it? Thanks very much.

**Comment by zengxianyu** [comment]
I tried several nicp but none of them works. Finally I found the [deformation transfer](https://github.com/Golevka/deformation-transfer), of which the first step ``corres_solve" is like a nicp and produces reasonable results
