### ISSUE TITLE
About the supplementary material of this paper

### ISSUE THREAD

**Issue by kuangcy1998** [zhuhao-nju/facescape#2]
Hi, thanks for your outstanding work and I'm waiting for the opening source code. I'm interested in the face registration steps and they are described in the supplementary material of your paper. How can I get access to the supplementary material? Thanks.

**Comment by zhuhao-nju** [comment]
Hi, we have just attached the supplementary material to the end of the arXiv paper.  
Please see https://arxiv.org/pdf/2003.13989.pdf
