### ISSUE TITLE
facial landmarks corresponding to the vertex id in mesh.

### ISSUE THREAD

**Issue by GuoxianSong** [zhuhao-nju/facescape#20]
Hi, Zhuhao, thanks to your great job and the dataset!

Can I have the vertex id in mesh corresponding to landmarks?
Thank you!

**Comment by deepmo24** [comment]
Want to know, too. Wish the authors can share the vertex id of facial landmarks. Thank you!

**Comment by zhuhao-nju** [comment]
Hi @GuoxianSong @deepmo24 ,

Here are the vertex ids saved in txt file, and the corresponding landmark indices visualized in the two pictures.
[landmark_indices.txt](https://github.com/zhuhao-nju/facescape/files/4879247/landmark_indices.txt)
![lm1](https://user-images.githubusercontent.com/40872587/86599602-6f06ad00-bfd1-11ea-80c8-2f0fa03a9d1d.jpg)
![lm2](https://user-images.githubusercontent.com/40872587/86599610-71690700-bfd1-11ea-817d-f457e58eb90a.png)

**Comment by cLEARLoVE00** [comment]
作者你好，我们是南京的一家AI公司，想做关于BFM模型重构的工作，主要用于数据增强。有些问题想要请教一下，能不能加个好友私聊，我的qq：1391570995，谢谢。
