### ISSUE TITLE
How to render texture to the 3DMM model?

### ISSUE THREAD

**Issue by deepmo24** [zhuhao-nju/facescape#22]
Hi, zhuhao:
Thanks for your great job and the dataset! I am eager to how to render texture to the 3DMM model of your dataset.  Just like you show in the 'Data Page'. Looking forward to hearing from you. Thank you!

![texture](https://user-images.githubusercontent.com/19352002/87521693-46f50900-c6b7-11ea-9459-07e619339aa3.png)

**Comment by zhuhao-nju** [comment]
Hi @deepmo24 ,
The model shown in the Data Page is one model provided in "facescape_trainset_***_***.zip".  It can be rendered with common renderer or 3D visualization tools.  
Our Bilinear model only contains geometry of base mesh, and do not contain texture.  So the models generated from our bilinear model cannot be rendered with texture.

**Comment by deepmo24** [comment]
Hi @zhuhao-nju ,
Thank you for your reply. In your paper, you use a pixel-level consistency loss in base model fitting. I think you need to render texture when using this loss. And in the supplementary, you said "The per-vertex albedo is represented as
a PCA model based on our dataset". Can you share some information on how to use texture on your model? Thank you!

**Comment by zhuhao-nju** [comment]
> Hi @zhuhao-nju ,
> Thank you for your reply. In your paper, you use a pixel-level consistency loss in base model fitting. I think you need to render texture when using this loss. And in the supplementary, you said "The per-vertex albedo is represented as
> a PCA model based on our dataset". Can you share some information on how to use texture on your model? Thank you!

Hi, our paper did use the bilinear model with vertex-color, which will be added to the download page soon.  I will keep you informed when the bilinear model are updated in this issue.  
Please note that due to alignment problems, texture (vertex color) generated from bilinear model is kind of blurry, not as clear as shown in the online-rendering demo.  The quality of texture in bilinear model may be improved in the future update.

**Comment by zhuhao-nju** [comment]
Hi @deepmo24 ,
The bilinear model with vertex-color is supplemented as facescape_bilinear_model_v1_3.zip in the download page.  The demo code is also updated.

**Comment by deepmo24** [comment]
Thank you!
