### ISSUE TITLE
Displacement Map的单位

### ISSUE THREAD

**Issue by goddice** [zhuhao-nju/facescape#23]
你好，请问在用displacement map做渲染的时候，缩放因子应该使用多少？谢谢

**Comment by zhuhao-nju** [comment]
Hi，渲染dp使用的缩放因子取值和软件相关，例如Data页面中静态渲染图是通过ZBrush渲染，缩放因子设定为0.014。
如需要把dpmap的值换算到实际尺度，可通过以下方式：dpmap的数据类型uint16，对应数值是0~65535；小于32768表示延法线向内，大于表示向外。关于尺度的确定，我们的多视点重建结果没有对应真实世界的尺度，而是按人内眼角的距离做了归一化。为了归一化到0~65535，缩放的系数是人为设定的，按一般人眼间距是40mm左右，可以这样算：((dpmap像素值-32768)/32768)*0.914等于实际的毫米距离。

**Comment by goddice** [comment]
> Hi，渲染dp使用的缩放因子取值和软件相关，例如Data页面中静态渲染图是通过ZBrush渲染，缩放因子设定为0.014。
> 如需要把dpmap的值换算到实际尺度，可通过以下方式：dpmap的数据类型uint16，对应数值是0-65535；小于32768表示延法线向内，大于表示向外。关于尺度的确定，我们的多视点重建结果没有对应真实世界的尺度，而是按人内眼角的距离做了归一化。为了归一化到0-65535，缩放的系数是人为设定的，按一般人眼间距是40mm左右，可以这样算：((dpmap像素值-32768)/32768)*0.914等于实际的毫米距离。

Thank you!

**Comment by xubaixinxbx** [comment]
hi, I met the same problem when I tried to add the 2D displacement map to the base model in TU-models.
I use the [code](https://github.com/zhuhao-nju/mvfr/blob/b63e826e21ee9a651b81ae9e5b4b0d1e390f65d2/dpmap_pred/.ipynb_checkpoints/test_dpmap2mesh-checkpoint.ipynb#L55), to displace the verts of the base model along the normal as the formula described.
 but the result is not what we expected, do you know how to use the trimesh or any other python tools to displace verts given the 2d displacement map?
![image](https://github.com/zhuhao-nju/facescape/assets/113180125/d8081198-4abc-4466-a73c-d3683d651ced)
