### ISSUE TITLE
The singular values from the 2-mode SVD

### ISSUE THREAD

**Issue by goddice** [zhuhao-nju/facescape#24]
你好，请问有可能提供一下你们的bilinear model的identity和expression参数对应的singular value吗？ 就是下图中的![CodeCogsEqn](https://user-images.githubusercontent.com/4031893/88438228-1569f500-cdbd-11ea-8ed2-dc5561f5dc73.gif)和![CodeCogsEqn (1)](https://user-images.githubusercontent.com/4031893/88438263-261a6b00-cdbd-11ea-8f49-9bab574c50f3.gif)， 谢谢！

![Screenshot from 2020-07-24 14-48-50](https://user-images.githubusercontent.com/4031893/88438132-d5a30d80-cdbc-11ea-8751-9d6d6235dcd2.png)

**Comment by yanght321** [comment]
你好。对id参数，你可以用factors_id_847_50_52.npy里所有样本的均值和方差做正则化。我们的bilinear model没有对exp的维度做分解，所以exp每一维仍然是blendshape表情的权重，一般在0-1之间，但并没有一个固定的先验分布。
