### ISSUE TITLE
Model use

### ISSUE THREAD

**Issue by cLEARLoVE00** [zhuhao-nju/facescape#25]
Dear author,thanks your opened code. I have a question that how to use your 3DMM model to recontruction face when I have a 2D face with 68 landmarks? Wait for your reply ,Thank you !

**Comment by zhuhao-nju** [comment]
Hi @cLEARLoVE00 ,
Fitting 3D face mesh to image is a classic application of the bilinear model.  I would suggest starting from Section IV-A of facewarehouse's TVCG2012 paper, which explians how to sovle this problem by energy optimization.  Recent works that use neural network to regress 3DMM also worth investigating.
