### ISSUE TITLE
 Tool code use

### ISSUE THREAD

**Issue by cLEARLoVE00** [zhuhao-nju/facescape#26]
I use tool code to process point cloud,meet a question"Failed to initialize Pyglet window with an OpenGL >= 3+ context.",I use code order to test code,but this question is hard to solve.

**Comment by zhuhao-nju** [comment]
It seems to be a problem with pyrender settings.  Could you try the example code of pyrender to see if it runs correctly?  --> https://pyrender.readthedocs.io/en/latest/examples/quickstart.html
