### ISSUE TITLE
about Registration of base shape

### ISSUE THREAD

**Issue by griffin-han** [zhuhao-nju/facescape#27]
你好，想请教下在supplemetary的Registration of base shape描述中，我看到“other 19 expressions”对齐使用了Deformation Transfer for Triangle Meshes的方法，是如facewarehouse使用了guide model么，这个guide model是如何获得的呢？

**Comment by yanght321** [comment]
是的，我们是使用了一套设计师预先做好的对应的19个表情的模型。

**Comment by griffin-han** [comment]
非常感谢！
