### ISSUE TITLE
About expression rigging

### ISSUE THREAD

**Issue by kuangcy1998** [zhuhao-nju/facescape#28]
Hi, thanks for keeping updating this project! Will you upload your tools for  expression rigging from generic blend-shapes?

**Comment by zhuhao-nju** [comment]
Hi, we are planning to release this part of code, and still need some time to tidy up, so there is not a shedule yet.  I will let you know when it is released.

**Comment by kuangcy1998** [comment]
> Hi, we are planning to release this part of code, and still need some time to tidy up, so there is not a shedule yet. I will let you know when it is released.

Thanks!

**Comment by ForrestPi** [comment]
> Hi, we are planning to release this part of code, and still need some time to tidy up, so there is not a shedule yet. I will let you know when it is released.

Have you released yet，which part of code is related to expression rigging.

**Comment by zhuhao-nju** [comment]
Hi @ForrestPi , the code and descriptions about rigging have been added here:
https://github.com/zhuhao-nju/facescape/blob/master/toolkit/demo_rig.ipynb
