### ISSUE TITLE
About the annotations of the provided 52 blendshapes

### ISSUE THREAD

**Issue by polukeadria** [zhuhao-nju/facescape#29]
Could you please provide the name for each blendshape in 
https://drive.google.com/file/d/1OuAUVMrBzEyRumOqFg3SUjehAUBK7Hn9/view?usp=sharing

**Comment by YUFENGZHANG** [comment]
Hi，Did you know the meaning of the each blendshape now? I have encounter this problem too!

**Comment by yanght321** [comment]
Hi, the names of the blendshapes can be found in the attachment.
[blendshape_names.txt](https://github.com/zhuhao-nju/facescape/files/5659587/blendshape_names.txt)
