### ISSUE TITLE
why not nromal map but displacement map？

### ISSUE THREAD

**Issue by Danny-QIN** [zhuhao-nju/facescape#3]
I think normal map is more important than displacement map in rendering.

**Comment by zhuhao-nju** [comment]
Hi, 
A displacement map can be transformed into a normal map, but a normal map cannot be precisely transformed to a displacement map, because of the ambiguity from normal to shape.  In short, the displacement map can represent real geometry more directly.

**Comment by Danny-QIN** [comment]
Hi,
I found the models in the paper have achived a high level,  did you use some commercial software like MataShape or RealityCapture? and which camera have you used in your project? I'm a newbie in 3D reconstruction and very interested in your research.

**Comment by zhuhao-nju** [comment]
> Hi,
> I found the models in the paper have achived a high level, did you use some commercial software like MataShape or RealityCapture? and which camera have you used in your project? I'm a newbie in 3D reconstruction and very interested in your research.

I have not used the two software you mentioned. As far as I know, most of the existing multi-view 3D reconstruction algorithms/software follow the classic SFM+MVS pipeline, which has achieved submillimeter accuracy in face reconstruction, in the case of high image quality. We used many DSLR cameras (Canon 700D, 650D, 5D, etc.) to get clear and high-resolution images, as image quality is quite important for 3D detail recovering.
