### ISSUE TITLE
single view reconstruction. 

### ISSUE THREAD

**Issue by umarmuzammil** [zhuhao-nju/facescape#30]
Hi there, congratulations. Your paper stands out looking compared to other similar papers.  I was wondering if you guys will release pre trained models for single image reconstruction ?

**Comment by zhuhao-nju** [comment]
Thanks! Yes, we plan to release the code and pre-trained model in the near future. I will let you know then.

**Comment by zhuhao-nju** [comment]
Hi, our code has been released here: https://github.com/yanght321/Detailed3DFace

**Comment by luoww1992** [comment]
@zhuhao-nju 
for help?
https://github.com/yanght321/Detailed3DFace/issues/13
