### ISSUE TITLE
Ground truth of displacement map

### ISSUE THREAD

**Issue by yfji** [zhuhao-nju/facescape#33]
Hi, thanks for your work, it's very impressive. I want to know the ground truth of the displacement map when you train the pix2pixHD model.  Like GAN training, I think there should be a dataset of displacement maps which is the "real images"

**Comment by zhuhao-nju** [comment]
Hi, the displacement map is part of the topology-uniformed model provided by FaceScape dataset.  To get them, you may apply for facescape dataset (at https://facescape.nju.edu.cn/) then download "Topologically Uniformed Model(TU-Model)" zip files, you will find them as png files in the zip package.

**Comment by yfji** [comment]
@zhuhao-nju Thanks a lot!

**Comment by yfji** [comment]
@zhuhao-nju Hi, thanks a lot for the reply! I want to apply for the dataset but the website you provide (https://facescape.nju.edu.cn/) is not available for me now, which must be visited using VPN

**Comment by zhuhao-nju** [comment]
@yfji We are very sorry that our campus network is under renovation, so the FaceScape website is temporarily inaccessible. The service will resume after 24:00PM, Nov 15, 2020, Beijing Time.  If you need the data as soon as possible, feel free to contact facescape@outlook.com where a temporal download link may be provided.

**Comment by yfji** [comment]
@zhuhao-nju Thanks a lot! I have another question about the paper. In equation (7), I think the "current blendshape weight" is the fitted expression parameter(maybe I'm wrong...), and what's the meaning of "fixed blendshape weight corresponding to the ith key expression"?

**Comment by zhuhao-nju** [comment]
Hi @yfji , "fixed blendshape weight corresponding to the ith key expression" means the weights to transform 52 bleandshapes to 20 TU models.  We do this because the bilinear model is built on the 52-expressions blendshapes, which is generated from 20 original expressions (detailed in Section 3.3), while our predicted displacement map is for the original 20 expressions.

**Comment by yfji** [comment]
Thanks for your reply! @zhuhao-nju
