### ISSUE TITLE
What package can be used for performing tucker decomposition to build bilinear model?

### ISSUE THREAD

**Issue by kuangcy1998** [zhuhao-nju/facescape#35]
Hi, I just want to ask what package can be used for doing tucker decomposition for such a huge tensor? Since I want to perform tucker decomposition on a similar tensor generated by me. I tried several packages but they all not support such huge data or the processing can be very very slow. I'll appreciate it a lot if you can tell me.

**Comment by zhuhao-nju** [comment]
Hi, we use "tensorly" to do tucker decomposition.  It's worth noting that our calculations require a very large amount of memory, close to 100G.

**Comment by Mr-bor** [comment]
Hi, can you tell me how to use tucker decomposition to get a core tensor and two low dimensional components about identity and expression? Since tensorly 's api tensorly.decomposition.Tucker() will return three factors from mode-1 to mode-3. I don't know much about this.
Thanks for your nice work!
