### ISSUE TITLE
What method to do mesh simplification?

### ISSUE THREAD

**Issue by yutaka329** [zhuhao-nju/facescape#36]
hi, thanks for your work。 I want to do mesh simplification, the mesh of model still have 29317 vertexs.  can you share the detail method or code  to do mesh reduction.

**Comment by zhuhao-nju** [comment]
Hi, I think you may try the functions in Meshlab.  It's in “Filters”--> "Reneshing, Simplification and Reconstruction" --> "Simplification: xxx".
