### ISSUE TITLE
how to use 300 model and some differert test result

### ISSUE THREAD

**Issue by luoww1992** [zhuhao-nju/facescape#38]
your work is very good!

when i use core_847_50_52.npy and  factor_id_847_50_52.npy to test it , it  show me a good result, 
but i get a error result if i use 300 model:core_847_300_52.npy.
error shows:

1, i check the code, i find it is wrong with id_mean.pkl and id_val.pkl, these are xx.pkl for 50, can you share the xx.pkl for 300 ?

2, what is the index_68.txt ? if i want to use my face landmark, how to get the index_68.txt, and the point number is only 68?

3, it is good in your default images, while i use my image to test it , face in my image is positive，close mouth and eyes,
but result is open eye and open mouse in xx.obj .  And the face if use --render  in render.jpg is  better than thexx.obj .

**Comment by yanght321** [comment]
1,  we find it is easy to overfit when fitting images with the 300 model. So we used the 50 model in our paper. The mean and variance can be calculated from factors_id_847_300_52.npy to use the 300 model.
2, index_68.txt is the manually labeled vertex indices of the 3D mesh corresponding to 68 dlib landmarks. You can edit the indices to use your landmark.
3, the result in render.jpg should be identical to the xx.obj. I'm not sure what caused the problem, you can check out if the landmark positions are correct.

**Comment by luoww1992** [comment]
@yanght321 

i notice the code use a file-- contour_line_68.pkl
if i use my landmarks,  how to change the file?
