### ISSUE TITLE
Downloaded obj file significantly differs from given ply file?

### ISSUE THREAD

**Issue by GGOSinon** [zhuhao-nju/facescape#39]
I'm trying to calculate landmarks of downloaded FaceScape Dataset using the code in tools/landmark/show_landmark.py.

However, I got super big coordinates (e.g. (880000, 76685) for 4344x 2896 image).

While digging to the code, I recognized that K and Rt significantly differs from ones in show_landmark.py (especially translation of Rt), and compared with tools/mview/projection_test.py which works fine. 

And I found that projection_test.py uses .ply file which has coordinates range of (-0.3, 7) while the .obj file had coordinates of (-87, 79) which differs a magnitude.

Are there additional scaling needed of obj files? Or am I missing something?

**Comment by zhuhao-nju** [comment]
Hi, the TU models (obj files) are aligned to the template model, while the multi-view models (ply files) uses the coordinate generated by structure-from-motion method, which is uncertain.  So projection_test.py can only work for multi-view models (ply files).  Initially we didn't plan to use TU models and multi-view models together, but if you want to align them, you can use this code:

# get Rt scale
with open("./Rt_scale_dict.json", 'r') as f:
    Rt_scale_dict = json.load(f)
    scale = Rt_scale_dict['%d'%id_index]['%d'%exp_index][0]
    Rt = np.array(Rt_scale_dict['%d'%id_index]['%d'%exp_index][1])

# align multi-view model to TU model
mv_mesh.vertices *= scale
mv_mesh.vertices = np.tensordot(Rt[:3,:3], mv_mesh.vertices.T, 1).T + Rt[:3, 3]

Rt_scale_dict.json can be downloaded here: https://drive.google.com/file/d/166wr9nj80bNwSmL3j2w6NIgUnwh9lxfP/view?usp=sharing

Please note this scale and Rt can not align these two models perfectly.  There is still minor misalignment.

**Comment by GGOSinon** [comment]
Ahhh I got the point

Thank you very much for the nice work and kind answer!
