### ISSUE TITLE
Is there a face with glasses in this dataset?

### ISSUE THREAD

**Issue by zhongtao93** [zhuhao-nju/facescape#4]
Hi, 

as title metioned, is there a face with glasses in this dataset, or how to resolve a face with glasses?

Thank you!

**Comment by zhuhao-nju** [comment]
Hi @zhongtao93 , all faces in this dataset do not contain glasses, as we aim to capture uncovered complete faces, and reconstructing glasses is very challenging to our capturing system.
Sorry to say that currently our dataset and single-view prediction method cannot tackle faces with glasses.
