### ISSUE TITLE
tools中有depth图像生成的代码吗？

### ISSUE THREAD

**Issue by billionfish** [zhuhao-nju/facescape#42]
想生成深度图用于3维人脸识别，但是dpmap不符合。
简介里说tools有生成代码 但是没找到？

**Comment by zhuhao-nju** [comment]
Hi @billionfish ,
参考projection_test的代码：https://github.com/zhuhao-nju/facescape/blob/master/tools/mview/projection_test.py
将第32行
    _, rend_img = renderer.render_cvcam(K, Rt, mesh_dirname, std_size=(h, w))
替换为
    depth_map, rend_img = renderer.render_cvcam(K, Rt, mesh_dirname, std_size=(h, w))
其中depth_map即是生成的深度图。

**Comment by billionfish** [comment]
> Hi @billionfish ,
> 参考projection_test的代码：https://github.com/zhuhao-nju/facescape/blob/master/tools/mview/projection_test.py
> 将第32行
> _, rend_img = renderer.render_cvcam(K, Rt, mesh_dirname, std_size=(h, w))
> 替换为
> depth_map, rend_img = renderer.render_cvcam(K, Rt, mesh_dirname, std_size=(h, w))
> 其中depth_map即是生成的深度图。

感谢回复
depth_map 生成的只有轮廓，并没有面部细节。我仔细学了pyrender的使用（如https://pyrender.readthedocs.io/en/latest/examples/quickstart.html ）还是无法得出能用于深度图人脸识别的图像。
分析可能的原因是与现实坐标转换的时候比例不对？
能指点下吗，谢谢！

**Comment by billionfish** [comment]
depthmap：![m2](https://user-images.githubusercontent.com/26395551/110121708-b01dbe00-7df9-11eb-8688-df16e3fb8120.jpg)
希望得到的深度图：
![1](https://user-images.githubusercontent.com/26395551/110121749-bf047080-7df9-11eb-9bb6-a60ca473d9ab.png)

**Comment by zhuhao-nju** [comment]
Hi @billionfish ，所生成的深度图是没问题的，之所以存出来只能看到轮廓，是因为背景的深度值为0，面部深度的变化区间 远小于 面部到背景的深度区间，导致所有内部细节损失在图像量化阶段了。

解决方法：
```
depth_map[depth_map!=0] = depth_map[depth_map!=0] - np.min(depth_map[depth_map!=0]) # move min to 0
depth_map = (depth_map / np.max(depth_map) * 255).astype(np.uint8) # scale max to 255
depth_map = 255 - depth_map # inverse depth_map as your example
cv2.imwrite("./depth_map.png", depth_map)
```
会获得这种结果：

![mv_result_49](https://user-images.githubusercontent.com/40872587/110207075-56ca9300-7ebc-11eb-8dfe-3c3b389f958a.jpg)

调节缩放尺度可以使面部细节更明显。

**Comment by billionfish** [comment]
谢谢你的回复，解决了我卡了很久的问题。
祝好！！
