### ISSUE TITLE
Publishable faces have data anonymization in it

### ISSUE THREAD

**Issue by vikasTmz** [zhuhao-nju/facescape#43]
Hi,

Thank you for releasing your data!

Among the 10 publishable faces, 8 of them have their eye region in the Albedo map anonymized. This isn't ideal when putting results on this data in our paper (qualitative evaluation is important in our work).

Do you have recommendations on how we should go about this?

**Comment by zhuhao-nju** [comment]
Hi @vikasTmz , I will find the Albedo map without mosaic, and sent to you in one or two days.

**Comment by vikasTmz** [comment]
Hi @zhuhao-nju, Thank you so much!

My email id: vikas_thamizharasan[at]brown[dot]edu
