### ISSUE TITLE
关于Facescape和FaceWarehouse数据的交换调用

### ISSUE THREAD

**Issue by darknessib** [zhuhao-nju/facescape#44]

**Comment by darknessib** [comment]
请问如果想要将FaceWarehouse或者别的数据集fit进Facescape的core_tensor.numpy和factor_id.numpy，需要进行怎样的数据处理呢？可否提供生成这两个文件的开源代码？

**Comment by zhuhao-nju** [comment]
Hi，我们暂时没有发布数据处理代码的打算。FaceScape和FaceWarehouse采用的人脸模板不同，融合二者的bilinear model要重跑模型对齐、处理等步骤，复杂且耗时。。

**Comment by darknessib** [comment]
那如果想单独将FaceWarehouse的数据整合成core_tensor.numpy和factor_id.numpy的形式是否可行呢（不将两个数据库融合）？如果可行的话需要进行哪些处理步骤？
