### ISSUE TITLE
Is scale = 0.2 mendatory for mview projection?

### ISSUE THREAD

**Issue by mfiro** [zhuhao-nju/facescape#45]
Hi, 
I have noticed that in the provided script here:
https://github.com/zhuhao-nju/facescape/blob/9fd4b836640c5026bda77f4cf87d2dd707e33ad4/tools/mview/projection_test.py#L42

the scale is set to 0.2. Does it have specific reason? I mean, if it's recommended value to render mview models.

**Comment by zhuhao-nju** [comment]
Hi @mfiro , it is not a recommended value, you can adjust scale according to your rendering resolution requirements.  I set it to 0.2 just because a small-resolution image can be loaded on page faster. If one wants 4K images, just set the scale to 1.0 or higher.

**Comment by zhuhao-nju** [comment]
Hi @mfiro , it is not a recommended value, you can adjust scale according to your rendering resolution requirements.  I set it to 0.2 just because a small-resolution image can be loaded on page faster. If one wants 4K images, just set the scale to 1.0 or higher.

**Comment by mfiro** [comment]
I understand. Thanks for this awesome work and your answers!
