### ISSUE TITLE
When will the dataset be released?

### ISSUE THREAD

**Issue by kuangcy1998** [zhuhao-nju/facescape#5]
Hi, I'm also working on 3D face reconstruction recently. 
Thanks for your outstanding work! Are you going to release the 3D dataset in recent months?

**Comment by zhuhao-nju** [comment]
Hi @kuangcy1998 ,
Yes, we are building the website for data distribution, which is scheduled to be online within one month.

**Comment by zhuhao-nju** [comment]
Hi @kuangcy1998 ,
The dataset is available for application and download at https://facescape.nju.edu.cn/.
Currently the 3D models (base mesh + displacement map + texture) are available, multi-view images will be released in the near future.

**Comment by kuangcy1998** [comment]
> Hi @kuangcy1998 ,
> The dataset is available for application and download at https://facescape.nju.edu.cn/.
> Currently the 3D models (base mesh + displacement map + texture) are available, multi-view images will be released in the near future.

Excited to hear that! Thanks for the contribution of your group!
