### ISSUE TITLE
About the constraints of the id and exp parameters to generate a face

### ISSUE THREAD

**Issue by FeastForU** [zhuhao-nju/facescape#50]
Firstly, thanks for your wonderful work
I’m trying to use the bilinear model v1.6 to generate random faces following your toolkit file demo_bilinear_basic.ipynb, the exact model I'm using is "facescape_bm_v1.6_847_50_52_id_front_new.npz". The problem is that when I choose random id and exp parameters, the generated face is usually distorted and werid. So I just want to know if there are some constraints of the id and exp parameters to randomly generate valid faces.

**Comment by zhuhao-nju** [comment]
Hi @FeastForU , 
To avoid weird and distorted faces, you should make the identity vectors follow the Gaussian distribution with the provided mean and variance value, like this:
```
random_id_vec = np.random.normal(model.id_mean, np.sqrt(model.id_var))
```

I have added some codes to generate random faces in demo_bilinear_basic.ipynb.

**Comment by FeastForU** [comment]
Thank u very much, I've seen the results in the latest demo_bilinear_basic.ipynb, it works well.
