### ISSUE TITLE
请使用VPN访问本网址

### ISSUE THREAD

**Issue by burningsoulll** [zhuhao-nju/facescape#51]
when visiting https://facescape.nju.edu.cn/,  I got "请使用VPN访问本网址"

**Comment by zhuhao-nju** [comment]
We are very sorry that due to the renovation of the campus network, the FaceScape website (https://facescape.nju.edu.cn/) is temporarily inaccessible during 2021/06/20--2021/07/10. The service will resume after 22:00PM, July 10, 2021.
