### ISSUE TITLE
blendshapes names

### ISSUE THREAD

**Issue by 15652309372** [zhuhao-nju/facescape#52]
There are 52 blendshapes. Do these blendshapes have names corresponding to facs?

**Comment by zhuhao-nju** [comment]
Hi, here are the names of blendshapes: 
1 EyeBlink_L
2 EyeBlink_R
3 EyeSquint_L
4 EyeSquint_R
5 EyeDown_L
6 EyeDown_R
7 EyeIn_L
8 EyeIn_R
9 EyeOpen_L
10 EyeOpen_R
11 EyeOut_L
12 EyeOut_R
13 EyeUp_L
14 EyeUp_R
15 BrowsD_L
16 BrowsD_R
17 BrowsU_C
18 BrowsU_L
19 BrowsU_R
20 JawOpen
21 LipsTogether
22 JawLeft
23 JawRight
24 JawFwd
25 LipsUpperUp_L
26 LipsUpperUp_R
27 LipsLowerDown_L
28 LipsLowerDown_R
29 LipsUpperClose
30 LipsLowerClose
31 MouthSmile_L
32 MouthSmile_R
33 MouthDimple_L
34 MouthDimple_R
35 LipsStretch_L
36 LipsStretch_R
37 MouthFrown_L
38 MouthFrown_R
39 MouthPress_L
40 MouthPress_R
41 LipsPucker
42 LipsFunnel
43 MouthLeft
44 MouthRight
45 ChinLowerRaise
46 ChinUpperRaise
47 Sneer_L
48 Sneer_R
49 Puff
50 CheekSquint_L
51 CheekSquint_R

**Comment by 15652309372** [comment]
thanks

**Comment by ForrestPi** [comment]
@zhuhao-nju   

> Hi, here are the names of blendshapes: 1 EyeBlink_L 2 EyeBlink_R 3 EyeSquint_L 4 EyeSquint_R 5 EyeDown_L 6 EyeDown_R 7 EyeIn_L 8 EyeIn_R 9 EyeOpen_L 10 EyeOpen_R 11 EyeOut_L 12 EyeOut_R 13 EyeUp_L 14 EyeUp_R 15 BrowsD_L 16 BrowsD_R 17 BrowsU_C 18 BrowsU_L 19 BrowsU_R 20 JawOpen 21 LipsTogether 22 JawLeft 23 JawRight 24 JawFwd 25 LipsUpperUp_L 26 LipsUpperUp_R 27 LipsLowerDown_L 28 LipsLowerDown_R 29 LipsUpperClose 30 LipsLowerClose 31 MouthSmile_L 32 MouthSmile_R 33 MouthDimple_L 34 MouthDimple_R 35 LipsStretch_L 36 LipsStretch_R 37 MouthFrown_L 38 MouthFrown_R 39 MouthPress_L 40 MouthPress_R 41 LipsPucker 42 LipsFunnel 43 MouthLeft 44 MouthRight 45 ChinLowerRaise 46 ChinUpperRaise 47 Sneer_L 48 Sneer_R 49 Puff 50 CheekSquint_L 51 CheekSquint_R

some blendshape names are not matched arkit blendshape names?
mouthTogether
mouthUpperClose
mouthLowerClose
ChinLowerRaise
ChinUpperRaise
cannot find in arkit blendshape
