### ISSUE TITLE
Can we transfer the bilinear model to separate linear form?

### ISSUE THREAD

**Issue by FeastForU** [zhuhao-nju/facescape#53]
In FaceScape, we use bilinear model to get a face shape: ![](https://render.githubusercontent.com/render/math?math=$V=C_r*\omega_{exp}*\omega_{id}$). Can we transfer it to the usual form: ![](https://render.githubusercontent.com/render/math?math=$V=\overline{V}$) + ![](https://render.githubusercontent.com/render/math?math=$B_{id}*\omega_{id}$) + ![](https://render.githubusercontent.com/render/math?math=$B_{exp}*\omega_{exp}$), where  ![](https://render.githubusercontent.com/render/math?math=$\overline{V}$) is the mean shape,  ![](https://render.githubusercontent.com/render/math?math=$B_{id}$) is the identity basis and ![](https://render.githubusercontent.com/render/math?math=$B_{exp}$) is the expression basis?
If so, how can we do that?

**Comment by zhuhao-nju** [comment]
Hi, I am afraid it cannot be directly transformed into the expression as you described. The most close solution is:
![image](https://user-images.githubusercontent.com/40872587/125749763-2404cb0f-5d3d-44e4-9eca-e1456724fbe0.png)
