### ISSUE TITLE
关于全脸拟合的代码和数据集ID对应关系问题

### ISSUE THREAD

**Issue by MingwuZheng** [zhuhao-nju/facescape#56]
你好，感谢FaceScape精彩的工作！

- 请问有没有使用参数模型拟合整张脸的代码？（而非有限的关键点）
- 请问多视角数据和TU数据ID对应关系是怎样的？同样的序号对应同样的人吗？

谢谢！

**Comment by caozhenxiang-kouji** [comment]
同问，TU模型和多视角的对应关系到底是怎么样的
