### ISSUE TITLE
vertices and faces indices not match in facescape_bm_v1.6_847_50_52_id_front.npz

### ISSUE THREAD

**Issue by mingsjtu** [zhuhao-nju/facescape#57]
The model file facescape_bm_v1.6_847_50_52_id_front.npz.
I found in bm_model['fv_indices_front'] , the max index is 26317. But the shape of bm_model['frontal_vert_num'] is (26278, 3), which means there are only 26278 vertices. This cause the following error when I run the toolkit file demo_bilinear_basic.ipynb.

IndexError: index 26278 is out of bounds for axis 0 with size 26278
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_20515/2181680429.py in <module>
     39                [0, 0, -1, 500]], dtype=np.float64)
     40 
---> 41 depth_full, image_full = render_cvcam(trimesh.Trimesh(vertices = mesh_full.vertices, 
     42                                                       faces = mesh_full.faces_v-1),
     43                                       Rt = Rt)

**Comment by zhuhao-nju** [comment]
Hi @mingsjtu , thanks for pointing out this problem!

I have checked it, and found that the wrongly released files during 2021/09/07--2021/09/18 caused this problem.  I have updated these files, so re-downloading "facescape_bm_v1.6_847_50_52_id_front.npz" will solve this problem.

For other friends referring this issue, if you downloaded the parametric model files (npz files) during 2021/09/07--2021/09/18, please re-download them as some face_vertex_index related parameters were wrong.

**Comment by prathebaselva** [comment]
Still downloading the files give this issue. Can you please reverify.

**Comment by xiyichen** [comment]
Same issue. Still only have 26278 vertices from the 1.6 model. @prathebaselva Have you been able to find the right file?
