### ISSUE TITLE
ground truth of Displacement Map 是如何获取的

### ISSUE THREAD

**Issue by 675492062** [zhuhao-nju/facescape#58]
1）怎样计算出所给UV贴图的motion Map？
2）能公布对多视角图像配准的工具包吗？

**Comment by zhuhao-nju** [comment]
Hi,

It seems the title and the content are different questions.

For ground-truth of displacement map, we firstly smooth the raw scan model (refered as multi-view model in downloading page) to obtain the rough model, then compute the difference between the rough model and raw scan model along normal direction as displacement. These displacement are resampled in UV space by barycentric interpolation, forming diplacement map.

For motion map, I guess you mean the motion map refered in our paper (fig4). We first compute the 3D vertex movement between a certain expression and neutral expression, then resample the movements to UV space by barycentric interpolation.

We are not releasing the code for multi-view registration recently.
