### ISSUE TITLE
Dataset Release and Raw Scan

### ISSUE THREAD

**Issue by yhw-yhw** [zhuhao-nju/facescape#6]
Hi, when will the dataset be released and will you release the raw scans?

**Comment by zhuhao-nju** [comment]
Hi @yhw-yhw , the data should be released in about one week.  
The raw data will not be released as it is really really huge.  The transformed representation of "base mesh + displacement map" takes roughly 2% of the original mesh data size, while maintaining the mean absolute error to be less than 0.3mm.
