### ISSUE TITLE
facescape_bm_v1.6_847_300_52_id.npz文件的疑问

### ISSUE THREAD

**Issue by changfali** [zhuhao-nju/facescape#61]
您好，感谢您所作的工作！关于facescape_bm_v1.6_847_300_52_id.npz这个文件，有个疑问：
'id_mean'这个数据的维度为什么是50而不是300呢？

**Comment by zhuhao-nju** [comment]
The problem of wrong 'id_mean' in facescape_bm_v1.6_847_300_52_id.npz has been fixed. The updated files can be re-downloaded from the original links.

**Comment by lyx323** [comment]
已收到
