### ISSUE TITLE
关于轮廓线的疑问

### ISSUE THREAD

**Issue by changfali** [zhuhao-nju/facescape#64]
您好，我正在使用v1.3版本的模型测试，有几个疑问想问下：
- 请问是否有v1.3版本对应的基于关键点的拟合代码呢？
- v1.6版本的代码中包含的contour_line_right和contour_line_left是否可以直接使用到1.3版本呢？
- 拟合的过程中为什么使用高斯混合模型而非单纯的l1或者l2正则呢？优势是什么呢？ @WangYanru-NJU @zhuhao-nju @yanght321

**Comment by zhuhao-nju** [comment]
Hi, sorry for the late reply,

- The landmark-based fitting for ver1.3 can be found here: https://github.com/yanght321/Detailed3DFace/blob/master/bilinear_model.py
- The contour_line index of v1.6 can be transformed into v1.3 using 'vert_16to10_dict.npy' in the npz files.
- This is an empirical choise, as we find GaussianMixture quantitatively better in fitting accuracy.
