### ISSUE TITLE
About the texture model

### ISSUE THREAD

**Issue by kuangcy1998** [zhuhao-nju/facescape#65]
Hello, thanks for keep updating the FaceScape model!

I just have a question when I use the texture basis. Is the texture model able to cover for various skin color, like black color or a pale face?  I tried to play with the texture model by randomly setting the texture parameters but the output color are always like an Asian face .
By the way, I just have another question about the 52 blendshapes. Do they have some correspondences with facial action unit or facial expressions? 

Looking forward to your reply!

**Comment by zhuhao-nju** [comment]
Hi, 

Currently, our texture model cannot cover black color and pale faces, as they are generated by applying PCA to FaceScape data most of which are Asian faces.

The 52 blendshapes correspond to some specific facial expressions. Please refer to #29 .
