### ISSUE TITLE
Texture unwrapping for detailed textured face reconstruction

### ISSUE THREAD

**Issue by mjvanderboon** [zhuhao-nju/facescape#67]
Hi,

Thank you for the great model. I was wondering if there is a functionality available for the 1.6 model that can unwrap the texture from a given source image and fitted model so it can be used on the detailed reconstruction pipeline (similar to https://github.com/yanght321/Detailed3DFace).

**Comment by zhuhao-nju** [comment]
Thanks for your contribution! The code has been verifed and merged :D
