### ISSUE TITLE
大佬请问一下

### ISSUE THREAD

**Issue by Oviea** [zhuhao-nju/facescape#68]
![image](https://user-images.githubusercontent.com/41980406/142177128-1f68577a-bab0-424e-afe9-74f398792c10.png)
这三个矩阵是干嘛的呀， 不太理解每个具体 下标的含义
望解答
3Q~~

**Comment by zhuhao-nju** [comment]
Hi, 

K is the intrinsic matrix; Rt is the extrinsic matrix (rotation + translation); R_cv2gl is the transforming matrix from cv camera coordinate (commonly used in computer vision) to gl camera coordinate (defined by OpenGL). R_cv2gl should be applied to extrinsic matrix if you are using cv camera coordinate.
