### ISSUE TITLE
Implementation of the standard evaluation code to measure the accuracy

### ISSUE THREAD

**Issue by Bornblack** [zhuhao-nju/facescape#69]
Hi,
Can you share the code to evaluate the single-view facial 3d reconstrution error (including MNE, CD, CR)  for the FaceScape dataset？
@WangYanru-NJU @yanght321 
Thanks!

**Comment by zhuhao-nju** [comment]
Hi @Bornblack ,

We are nearly ready to add the evaluation code to this repositary, which should be done within one week.
