### ISSUE TITLE
Amount of UV coordinates not corresponding with amount of vertices in v1.6 model

### ISSUE THREAD

**Issue by mjvanderboon** [zhuhao-nju/facescape#73]
Hi,

In the v1.6 model the numbers of vertices, 26278, does not correspond with the number of texture coordinates, 26364. This seems to cause wrongly unwrapped textures when trying to render a model using `pyrender`.

I believe the cause to be related to the merging or unmerging of vertices. The following pseudocode shows how to correct the issue. 
```
_, mask_v, mask_vt = trimesh.visual.texture.unmerge_faces(bm.fv_indices-1, bm.ft_indices-1, maintain_faces=False)
mesh.update_vertices(mask_v)
uv = model.texcoords[mask_vt]
mesh.visual = trimesh.visual.texture.TextureVisuals(uv=uv, image=_texture_)
```
This results in a `Trimesh` mesh with a correct `.visual` for rendering. 

I believe the above would not be necessary if the uv coordinates in the model corresponded to the vertices the model outputs.

**Comment by zhuhao-nju** [comment]
Thanks for reporting this problem!

As you point out, some vertices in our mesh model are corresponding to two texture coordinates, while pyrender and trimesh do not support this (Meshlab and our obj loader support it). These vertices lie on the seaming edge in the back of the head, so they are split into two coordinates in the UV space. I think they are necessary and OBJ format does support this. 

Fortunately, the 'load_mesh()' function in trimesh automatically split one vertex into two to achieve one-to-one mapping between v and vt. So I think it is OK to keep the current vertices and texture_coordinate unchanged. If one would like to render with pyrender, just load the mesh with trimesh.load_mesh first, like the code in:

https://nbviewer.org/github/zhuhao-nju/facescape/blob/master/toolkit/demo_render.ipynb
