### ISSUE TITLE
How to render the mesh with texture

### ISSUE THREAD

**Issue by Songluchuan** [zhuhao-nju/facescape#74]
Thanks for your amazing work on facescape and updating for this repo. However, about this code, I want to know how to use the `facescape_fitter.get_texture` to to color the vertices？

For example, after I use the facescape_fitter.get_texture, I get the texture_map, than I try to use the code like :

```
def texcoords2vertexcolor(mesh, texture_image):
    tmp = np.zeros_like(texture_image)
    v_count = len(mesh.vertices)
    vertex_colors = np.zeros((v_count, 3))
    idx = 0
    for tc in mesh.texcoords:
        if idx >= v_count: #b/c mesh somehow has more texcoords than vertices. # TODO look into this
            break
        # Read image at texcoord
        i = int(tc[0] * texture_image.shape[0])
        j = int(tc[1] * texture_image.shape[1])
        vertex_colors[idx, :] = texture_image[i, j]
        tmp[i, j] = texture_image[i, j]
        idx += 1
    return vertex_colors, tmp
```

than, vertex_colors=mesh_full.vert_colors in the trimesh.Trimesh, I cannot get the correct face with color. The results are as follows
![007a73b9a77d9afeca1d304db6bca2e](https://user-images.githubusercontent.com/42260891/146481110-f20a655a-916c-4762-a844-ea0a12cd0764.png)

After with vertex_colors:

![e48a447c02ce66263121b6664459fcd](https://user-images.githubusercontent.com/42260891/146481138-2343e4fe-0b8a-423e-b582-164fe67ff3cf.png)

I will be very grateful for your reply.

**Comment by zhuhao-nju** [comment]
Hi,

The vertices and texture_coordinates are stored in a different order, so the correspondence between vertice and texture_coordinate in your code is incorrect.  You should find the correspondences in the face_vertex_indices. 

For example, one line in the OBJ file - "f 1/1 6590/2 6591/3" means the 1st vertex corresponds to the 1st texture coordinate; the 6590th vertex corresponds to the 2nd texture_coordinate; 6591st vertex corresponds to 3rd texture_coordinate.
