### ISSUE TITLE
MVS

### ISSUE THREAD

**Issue by lxy2017** [zhuhao-nju/facescape#76]
Hi, I want to use your multi-view images for 3D reconstruction, what algorithm suggest?  colmap or openmvs?

**Comment by zhuhao-nju** [comment]
Both should be good, but I didn't verify their performance for face reconstruction.

If you just want robust performance and don't dig deep into the algorithm, I think some business softwares (e.g. Agisoft Metashape) are better choices as many engineering optimizations have been involved.

**Comment by lxy2017** [comment]
Thanks! Is the original model reconstructed in the paper obtained using the software Agisoft Metashape? Or other algorithms, can you tell me this? If not, can you give me some suggestions if I want to get similar results?

**Comment by zhuhao-nju** [comment]
We used the algorithm implemented by ourselves, mainly referring to these two works:
Accurate, Dense, and Robust Multi-View Stereopsis, PAMI2010
High-Quality Single-Shot Capture of Facial Geometry, SIGGRAPH2010

**Comment by lxy2017** [comment]
Thank you very much for your patience reply！Are the camera parameters estimated through the SFM algorithm or obtained through calibration?

**Comment by zhuhao-nju** [comment]
> Thank you very much for your patience reply！Are the camera parameters estimated through the SFM algorithm or obtained through calibration?

We used SFM. Calibration will work as well, but every time the camera system is adjusted, it needs to be re-calibrated which is very annoying. Besides, calibration will be the only option if the camera array is too sparse, since SFM is very unstable when the overlap of viewing fields is reduced.
