### ISSUE TITLE
About benchmark evaluation for DECA model

### ISSUE THREAD

**Issue by yjhong89** [zhuhao-nju/facescape#82]
Dear author,

I am trying to evaluate my DECA model against released FACESCAPE evaluation dataset.

When preprocess image to 224x224 in DECA, there is a scale factor which controls size of center cropped image based on bbox. 
I wonder what a scale factor is used when preprocessing images in FACESCAPE evaluation dataset [(1.6 in NoW (DECA official repo))](https://github.com/YadiraF/DECA/blob/f84855abf9f6956fb79f3588258621b363fa282c/decalib/datasets/now.py#L13)

Thank you,
Best regards,
YJHong.

**Comment by zhuhao-nju** [comment]
Hi YJHong,

Considering that different methods use different preprocessing, we used default normalizing scale provided by each methods, then transform their result back to the original image coordinate for evaluation. The face scale of the original image is the same as the source images in CelebA and AFLW dataset.

**Comment by yjhong89** [comment]
@zhuhao-nju 
That's why "tform" from estimate_transform is also saved, to result back to the original image coordinate. 

Thanks for your reply!

**Comment by yjhong89** [comment]
@zhuhao-nju 

Sorry but have few questions ?
- As you know, 3d benchmarks such as NoW or Feng (fg2018) should neutralize pose and expression, there is no need to neutralize pose and expression for facescape ? 
Is it right just saving obj, cam, tform for each image ?
- In benchmark/code/evaluator.py , default iter_num for fslab is set to 660. Is there any reason why setting iter_num to 660 ? There are 523 images in "lab_img"

Thank you!

**Comment by zhuhao-nju** [comment]
@yjhong89 
* Yes, this benchmark aims to evaluate the shape recovery at the moment the photo is taken, involving expression and pose. So it doesn't neutralize pose and expressions, which is a difference from NoW benchmark.
* Thanks for pointing out this! Some images are missed in the transfering and compressing. I have updated the shared files, delete data.zip and re-run "./download_data.sh" will get all 660 images.

**Comment by yjhong89** [comment]
@zhuhao-nju 
Thank you!
