### ISSUE TITLE
factor_id

### ISSUE THREAD

**Issue by wuneng** [zhuhao-nju/facescape#86]
In v1.6, factor id is missing. Is there a file contain it?

**Comment by HowieMa** [comment]
Same problems. Have you found it?  
In V1.3, we have "data/factors_id_847_50_52.npy" with shape (847, 50), thus we can get the identity weights for each subject.

**Comment by lyx323** [comment]
已收到

**Comment by 123456789asdfjkl** [comment]
Same problems. Have you found it? @wuneng

**Comment by lyx323** [comment]
已收到
