### ISSUE TITLE
mesh models with extension .ply

### ISSUE THREAD

**Issue by SaharHusseini** [zhuhao-nju/facescape#88]
Hello,

First of all, thank you for your good job. I have a question regarding the raw mesh models with extension .ply. I was able to find one sample raw mesh with high details (4_anger.ply). Could you please tell me what is the best way to reconstruct a similar high detailed mesh for the rest of the dataset?

**Comment by lyx323** [comment]
已收到

**Comment by SaharHusseini** [comment]
If we do not have mesh.ply files, could you please tell me how I can create it for a person in a certain expression?
