### ISSUE TITLE
关于52exp数据集和数据集中的一些问题

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [zhuhao-nju/facescape#9]
非常赞的工作！

可以分享全部id的52exp的原数据或者bilinear模型么，并且我有几个问题:
1. nature的嘴大概率是张开的，请问这是正常的么
2. 20exp中有不少badcase，这是否会通过example rig的方法去消除，还是需要人工修改？

**Comment by zhuhao-nju** [comment]
谢谢！@ZHANG-SHI-CHANG 
目前我们没有发布52exp的数据的计划，这些数据是可以从发布的20exp模型生成的。
问题1：对于raw scanned model，中立表情的嘴部绝大部分是闭合的。由于我们采用的template mesh是上下唇分离的，NICP处理后的模型会出现嘴缝处表面不完整，导致转化后的嘴部呈轻微张开。
问题2：因为我们的对齐是完全自动的，不可避免会因为特征点位置不准、初始对齐位置不准等原因出现badcase。可以参考example rig的文章，从20exp到52exp是个优化的过程，可以通过调整每项损失的权重，使得到的blendshape更接近采集的模型或者更接近单纯的deformation transfer。合适的权重下，得到的52exp能够在保留原始数据特征的同时一定程度上减小采集或者对齐过程的artifacts。如果人工修改badcase效果会更好。
![image](https://user-images.githubusercontent.com/40872587/84781328-45351880-b019-11ea-9619-7407df0415fe.png)

**Comment by ZHANG-SHI-CHANG** [comment]
非常的好！近期我会在之前的方法上尝试用facescape替换facewarehouse，期待有大的提升！
