### ISSUE TITLE
camera intrinsics and extrinsics

### ISSUE THREAD

**Issue by X-niper** [zhuhao-nju/facescape#90]
Hi, thanks for sharing this work and the high-quality dataset!

You share the original multi-view camera figure together with the TU-model. I found that the camera intrinsics and extrinsics you provide are different between different scanning. The question is that,  the camera parameters, which are in param.json file, are inferred from multi-view photogrammetry or measured/provided according to the hardware. 

I think it's more reasonable to provide the original camera parameters that are determined by your setup because they can be used  in multi-view photogrammetry. Then, if they are provided according to the hardware, why they differ between different scanning? 

Your response are much appreciated!

**Comment by zhuhao-nju** [comment]
Hi @X-niper ,

We captured the data using multiple hardware setups, which are located in two places for the convenience to capture different people. For different setups, the position and pose of the cameras have been adjusted, so we don't have an uniform intrinsic/extrinsic parameters for all the tuples of images. 

In the 3D reconstruction phase, we used structure-from-motion to solve intrinsic and extrinsic parameters for each tuple of images, which can be understood as self-calibration. So the intrinsic/extrinsic parameters obtained are different. We provide global rotation/translation and scale parameters for each tuple to align them in a canonical space (https://github.com/zhuhao-nju/facescape/blob/master/toolkit/demo_align.ipynb), but they are only approximately aligned.

**Comment by X-niper** [comment]
> Hi @X-niper ,
> 
> We captured the data using multiple hardware setups, which are located in two places for the convenience to capture different people. For different setups, the position and pose of the cameras have been adjusted, so we don't have an uniform intrinsic/extrinsic parameters for all the tuples of images.
> 
> In the 3D reconstruction phase, we used structure-from-motion to solve intrinsic and extrinsic parameters for each tuple of images, which can be understood as self-calibration. So the intrinsic/extrinsic parameters obtained are different. We provide global rotation/translation and scale parameters for each tuple to align them in a canonical space (https://github.com/zhuhao-nju/facescape/blob/master/toolkit/demo_align.ipynb), but they are only approximately aligned.

**Comment by X-niper** [comment]
Hi, @zhuhao-nju 
So glad to hear your response!
 I found that camera parameters are different even for **scans that belong to one person but different expression** . Does this mean that the parameters you provide are self-calibrated? 
Again, than you so much for this work and your response:>

**Comment by X-niper** [comment]
Another question is as follows. To get multi view model (.ply file) from multi-view data (many .jpg files), do you use commercial software such as Metashape or your own tools ?

**Comment by zhuhao-nju** [comment]
Hi @X-niper ,
Yes, these parameters are obtained by self-calibration that is the same thing as structure-from-motion mentioned earlier. We used our own tools, while Metashape should work as well, both of which are based on structure-from-motion and multi-view stereo algorithms.

**Comment by SaharHusseini** [comment]
Hello @X-niper,

I noticed that you are also working on this dataset. Could you please help me with this issue?

I was not able to download the dataset from the website but using the google drive share link I was able to download them. My problem is that I can not find the 3D mesh models corresponding to the multi-view images (.ply files), the meshes
explained in the following link

https://github.com/zhuhao-nju/facescape/blob/master/doc/doc_mview_model.md

MESH_ROOT
#     ↓ID    ↓EXP
├───── 1
│      ├── 1_neutral.ply
│      ├── 2_smile.ply
│      ├── ...             
│      └── 20_brow_lower.ply
├───── 2
├───── ...
└───── 359

I would like to know how you downloaded the data and do you have the multiview meshes for each set of images? 

Thank you for your help

Best regards,
Sahar
